language: csharp
sudo: required
dist: xenial
services:
  - docker
solution: CreditRisks.sln
mono: none
dotnet: 2.2.104
before_script:
  - dotnet restore
script:
  - dotnet test
  - docker build -t app .
  - docker login docker.pkg.github.com --username asciishell -p $TOKEN
  - docker tag app docker.pkg.github.com/goo-goo-goo-joob/creditrisks/app:1.0
  - docker push docker.pkg.github.com/goo-goo-goo-joob/creditrisks/app:1.0
  - docker logout