jobs:
  include:
    - stage: test
      name: "C# test"
      language: csharp
      solution: CreditRisks/CreditRisks.sln
      mono: none
      dotnet: 2.2.104
      before_script:
        - cd CreditRisks
        - dotnet restore
      script:
        - dotnet test

    - stage: build_and_deploy
      language: bash
      sudo: required
      dist: xenial
      services:
        - docker
      script:
        - docker build -t app CreditRisks/Dockerfile .
      deploy:
        provider: script
        skip_cleanup: true
        on:
          condition:  "$TRAVIS_BRANCH = master || ! $TRAVIS_TAG"
        script: make docker-deploy