jobs:
  include:
    - stage: test
      name: "C# test"
      language: csharp
      sudo: required
      dist: xenial
      services:
        - docker
      solution: CreditRisks/CreditRisks.sln
      mono: none
      dotnet: 2.2.104
      before_script:
        - cd CreditRisks
        - dotnet restore
      script:
        - dotnet test
        - docker build -t app .

    - stage: deploy
      script: cd CreditRisks
      deploy:
        provider: script
        skip_cleanup: true
        on:
          condition:  "$TRAVIS_BRANCH" = "master" || ! "$TRAVIS_TAG"
        script: make docker-deploy