# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calc_service.proto',
  package='calcservice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63\x61lc_service.proto\x12\x0b\x63\x61lcservice\"I\n\x0b\x43\x61lcRequest\x12\x0b\n\x03INN\x18\x01 \x01(\t\x12-\n\talgorithm\x18\x02 \x01(\x0e\x32\x1a.calcservice.AlgorithmType\" \n\tCalcReply\x12\x13\n\x0bProbability\x18\x01 \x01(\x02*4\n\rAlgorithmType\x12\x10\n\x0c\x44\x45\x46\x41ULT_HAND\x10\x00\x12\x11\n\rDECISION_TREE\x10\x01\x32T\n\x0b\x43\x61lcService\x12\x45\n\x0f\x43\x61lcProbability\x12\x18.calcservice.CalcRequest\x1a\x16.calcservice.CalcReply\"\x00\x62\x06proto3')
)

_ALGORITHMTYPE = _descriptor.EnumDescriptor(
  name='AlgorithmType',
  full_name='calcservice.AlgorithmType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT_HAND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECISION_TREE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=144,
  serialized_end=196,
)
_sym_db.RegisterEnumDescriptor(_ALGORITHMTYPE)

AlgorithmType = enum_type_wrapper.EnumTypeWrapper(_ALGORITHMTYPE)
DEFAULT_HAND = 0
DECISION_TREE = 1



_CALCREQUEST = _descriptor.Descriptor(
  name='CalcRequest',
  full_name='calcservice.CalcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='INN', full_name='calcservice.CalcRequest.INN', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='calcservice.CalcRequest.algorithm', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=108,
)


_CALCREPLY = _descriptor.Descriptor(
  name='CalcReply',
  full_name='calcservice.CalcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Probability', full_name='calcservice.CalcReply.Probability', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=142,
)

_CALCREQUEST.fields_by_name['algorithm'].enum_type = _ALGORITHMTYPE
DESCRIPTOR.message_types_by_name['CalcRequest'] = _CALCREQUEST
DESCRIPTOR.message_types_by_name['CalcReply'] = _CALCREPLY
DESCRIPTOR.enum_types_by_name['AlgorithmType'] = _ALGORITHMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalcRequest = _reflection.GeneratedProtocolMessageType('CalcRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCREQUEST,
  '__module__' : 'calc_service_pb2'
  # @@protoc_insertion_point(class_scope:calcservice.CalcRequest)
  })
_sym_db.RegisterMessage(CalcRequest)

CalcReply = _reflection.GeneratedProtocolMessageType('CalcReply', (_message.Message,), {
  'DESCRIPTOR' : _CALCREPLY,
  '__module__' : 'calc_service_pb2'
  # @@protoc_insertion_point(class_scope:calcservice.CalcReply)
  })
_sym_db.RegisterMessage(CalcReply)



_CALCSERVICE = _descriptor.ServiceDescriptor(
  name='CalcService',
  full_name='calcservice.CalcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=198,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalcProbability',
    full_name='calcservice.CalcService.CalcProbability',
    index=0,
    containing_service=None,
    input_type=_CALCREQUEST,
    output_type=_CALCREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCSERVICE)

DESCRIPTOR.services_by_name['CalcService'] = _CALCSERVICE

# @@protoc_insertion_point(module_scope)
